using VRCFaceTracking.Core.Params.Expressions;

namespace VRCFaceTracking.Babble;
public partial class BabbleOSC
{
    public TwoKeyDictionary<UnifiedExpressions, string, float> BabbleExpressionMap = new()
    {
        { UnifiedExpressions.NasalDilationRight, "/nasalDilationRight", 0f },
        { UnifiedExpressions.NasalDilationLeft, "/nasalDilationLeft", 0f},
        { UnifiedExpressions.NasalConstrictRight, "/nasalConstrictRight", 0f},
        { UnifiedExpressions.NasalConstrictLeft, "/nasalConstrictLeft", 0f},
        { UnifiedExpressions.CheekSquintRight, "/cheekSquintRight", 0f},
        { UnifiedExpressions.CheekSquintLeft, "/cheekSquintLeft", 0f},
        { UnifiedExpressions.CheekPuffRight, "/cheekPuffRight", 0f},
        { UnifiedExpressions.CheekPuffLeft, "/cheekPuffLeft", 0f},
        { UnifiedExpressions.CheekSuckRight, "/cheekSuckRight", 0f},
        { UnifiedExpressions.CheekSuckLeft, "/cheekSuckLeft", 0f},
        { UnifiedExpressions.JawOpen, "/jawOpen", 0f},
        { UnifiedExpressions.JawRight, "/jawRight", 0f},
        { UnifiedExpressions.JawLeft, "/jawLeft", 0f},
        { UnifiedExpressions.JawForward, "/jawForward", 0f},
        { UnifiedExpressions.JawBackward, "/jawBackward", 0f},
        { UnifiedExpressions.JawClench, "/jawClench", 0f},
        { UnifiedExpressions.JawMandibleRaise, "/jawMandibleRaise", 0f},
        { UnifiedExpressions.MouthClosed, "/mouthClosed", 0f},
        { UnifiedExpressions.LipSuckUpperRight, "/lipSuckUpperRight", 0f},
        { UnifiedExpressions.LipSuckUpperLeft, "/lipSuckUpperLeft", 0f},
        { UnifiedExpressions.LipSuckLowerRight, "/lipSuckLowerRight", 0f},
        { UnifiedExpressions.LipSuckLowerLeft, "/lipSuckLowerLeft", 0f},
        { UnifiedExpressions.LipSuckCornerRight, "/lipSuckCornerRight", 0f},
        { UnifiedExpressions.LipSuckCornerLeft, "/lipSuckCornerLeft", 0f},
        { UnifiedExpressions.LipFunnelUpperRight, "/lipFunnelUpperRight", 0f},
        { UnifiedExpressions.LipFunnelUpperLeft, "/lipFunnelUpperLeft", 0f},
        { UnifiedExpressions.LipFunnelLowerRight, "/lipFunnelLowerRight", 0f},
        { UnifiedExpressions.LipFunnelLowerLeft, "/lipFunnelLowerLeft", 0f},
        { UnifiedExpressions.LipPuckerUpperRight, "/lipPuckerUpperRight", 0f},
        { UnifiedExpressions.LipPuckerUpperLeft, "/lipPuckerUpperLeft", 0f},
        { UnifiedExpressions.LipPuckerLowerRight, "/lipPuckerLowerRight", 0f},
        { UnifiedExpressions.LipPuckerLowerLeft, "/lipPuckerLowerLeft", 0f},
        { UnifiedExpressions.MouthUpperUpRight, "/mouthUpperUpRight", 0f},
        { UnifiedExpressions.MouthUpperUpLeft, "/mouthUpperUpLeft", 0f},
        { UnifiedExpressions.MouthUpperDeepenRight, "/mouthUpperDeepenRight", 0f},
        { UnifiedExpressions.MouthUpperDeepenLeft, "/mouthUpperDeepenLeft", 0f},
        { UnifiedExpressions.NoseSneerRight, "/noseSneerRight", 0f},
        { UnifiedExpressions.NoseSneerLeft, "/noseSneerLeft", 0f},
        { UnifiedExpressions.MouthLowerDownRight, "/mouthLowerDownRight", 0f},
        { UnifiedExpressions.MouthLowerDownLeft, "/mouthLowerDownLeft", 0f},
        { UnifiedExpressions.MouthUpperRight, "/mouthUpperRight", 0f},
        { UnifiedExpressions.MouthUpperLeft, "/mouthUpperLeft", 0f},
        { UnifiedExpressions.MouthLowerRight, "/mouthLowerRight", 0f},
        { UnifiedExpressions.MouthLowerLeft, "/mouthLowerLeft", 0f},
        { UnifiedExpressions.MouthCornerPullRight, "/mouthCornerPullRight", 0f},
        { UnifiedExpressions.MouthCornerPullLeft, "/mouthCornerPullLeft", 0f},
        { UnifiedExpressions.MouthCornerSlantRight, "/mouthCornerSlantRight", 0f},
        { UnifiedExpressions.MouthCornerSlantLeft, "/mouthCornerSlantLeft", 0f},
        { UnifiedExpressions.MouthFrownRight, "/mouthFrownRight", 0f},
        { UnifiedExpressions.MouthFrownLeft, "/mouthFrownLeft", 0f},
        { UnifiedExpressions.MouthStretchRight, "/mouthStretchRight", 0f},
        { UnifiedExpressions.MouthStretchLeft, "/mouthStretchLeft", 0f},
        { UnifiedExpressions.MouthDimpleRight, "/mouthDimpleRight", 0f},
        { UnifiedExpressions.MouthDimpleLeft, "/mouthDimpleLeft", 0f},
        { UnifiedExpressions.MouthRaiserUpper, "/mouthRaiserUpper", 0f},
        { UnifiedExpressions.MouthRaiserLower, "/mouthRaiserLower", 0f},
        { UnifiedExpressions.MouthPressRight, "/mouthPressRight", 0f},
        { UnifiedExpressions.MouthPressLeft, "/mouthPressLeft", 0f},
        { UnifiedExpressions.MouthTightenerRight, "/mouthTightenerRight", 0f},
        { UnifiedExpressions.MouthTightenerLeft, "/mouthTightenerLeft", 0f},
        { UnifiedExpressions.TongueOut, "/tongueOut", 0f},
        { UnifiedExpressions.TongueUp, "/tongueUp", 0f},
        { UnifiedExpressions.TongueDown, "/tongueDown", 0f},
        { UnifiedExpressions.TongueRight, "/tongueRight", 0f},
        { UnifiedExpressions.TongueLeft, "/tongueLeft", 0f},
        { UnifiedExpressions.TongueRoll, "/tongueRoll", 0f},
        { UnifiedExpressions.TongueBendDown, "/tongueBendDown", 0f},
        { UnifiedExpressions.TongueCurlUp, "/tongueCurlUp", 0f},
        { UnifiedExpressions.TongueSquish, "/tongueSquish", 0f},
        { UnifiedExpressions.TongueFlat, "/tongueFlat", 0f},
        { UnifiedExpressions.TongueTwistRight, "/tongueTwistRight", 0f},
        { UnifiedExpressions.TongueTwistLeft, "/tongueTwistLeft", 0f},
        { UnifiedExpressions.SoftPalateClose, "/softPalateClose", 0f},
        { UnifiedExpressions.ThroatSwallow, "/throatSwallow", 0f},
        { UnifiedExpressions.NeckFlexRight, "/neckFlexRight", 0f},
        { UnifiedExpressions.NeckFlexLeft, "/neckFlexLeft", 0f}
    };
}
