namespace VRCFaceTracking.MediaPipe;
public partial class MediaPipeOSC
{
    public Dictionary<string, float> BabbleExpressionMap = new()
    {
        { "/_neutral", 0f }, //Unused
        {"/browDownLeft", 0f },
        {"/browDownRight", 0f },
        {"/browInnerUp", 0f },
        {"/browOuterUpLeft", 0f},
        {"/browOuterUpRight", 0f },
        {"/cheekPuff", 0f },
        {"/cheekSquintLeft", 0f },
        {"/cheekSquintRight",0f },
        {"/eyeBlinkLeft", 0f },
        {"/eyeBlinkRight",0f },
        {"/eyeLookDownLeft",0f },
        {"/eyeLookDownRight",0f },
        {"/eyeLookInLeft",0f },
        {"/eyeLookInRight",0f },
        {"/eyeLookOutLeft", 0f },
        {"/eyeLookOutRight", 0f },
        {"/eyeLookUpLeft", 0f },
        {"/eyeLookUpRight", 0f },
        {"/eyeSquintLeft",0f },
        {"/eyeSquintRight", 0f },
        {"/eyeWideLeft" ,0f},
        {"/eyeWideRight", 0f },
        {"/jawForward", 0f },
        {"/jawLeft", 0f },
        {"/jawOpen", 0f},
        {"/jawRight", 0f },
        {"/mouthClose", 0f },
        {"/mouthDimpleLeft", 0f },
        {"/mouthDimpleRight", 0f},
        {"/mouthFrownLeft",0f },
        {"/mouthFrownRight", 0f },
        {"/mouthFunnel", 0f },
        {"/mouthLeft", 0f },
        {"/mouthLowerDownLeft", 0f },
        {"/mouthLowerDownRight", 0f },
        {"/mouthPressLeft", 0f },
        {"/mouthPressRight",0f },
        {"/mouthPucker", 0f } ,
        {"/mouthRight", 0f },
        {"/mouthRollLower", 0f }, //Unused
        {"/mouthRollUpper", 0f }, //Unused
        {"/mouthShrugLower", 0f },
        {"/mouthShrugUpper", 0f },
        {"/mouthSmileLeft", 0f },
        {"/mouthSmileRight", 0f },
        {"/mouthStretchLeft", 0f },
        {"/mouthStretchRight",0f },
        {"/mouthUpperUpLeft", 0f },
        {"/mouthUpperUpRight", 0f },
        {"/noseSneerLeft", 0f },
        {"/noseSneerRight", 0f },
    };
}
